
package nahum;

import email.GetMsgMail;


/**
 *
 * @author Nahum Flores Gómez
 */
public class Info extends javax.swing.JDialog {
    private WriteRead leeEsc;
    private short pageNumber=0;
    private String infoPag="",urlInfo="";
    /**
     * Creates new form Info
     */
    public Info(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        pageNumber=0;
        readInfo();
        checkPage();
    }
    ////////////////////////////////////////////////////////////////////////////
    
    ////////////////////////////////////////////////////////////////////////////
    private void readInfo(){
        
        if (pageNumber==0) {
            urlInfo="Config/InfoSpanish1.lis";            
        }
        if (pageNumber==1) {
            urlInfo="Config/InfoSpanish2.lis";
        }
        leeEsc = new WriteRead();
        infoPag=leeEsc.leerGeneric(infoPag, urlInfo);
        txtAreaInfo.setText(infoPag);
        infoPag="";
    }
    ////////////////////////////////////////////////////////////////////////////
    private void checkPage(){
        if (pageNumber<=0) {
            bAnterior.setEnabled(false);
            bSiguiente.setEnabled(true);
        }else{
            bAnterior.setEnabled(true);
            if (pageNumber==1) {
                bSiguiente.setEnabled(false);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaInfo = new javax.swing.JTextArea();
        bCerrar = new javax.swing.JButton();
        bSiguiente = new javax.swing.JButton();
        bAnterior = new javax.swing.JButton();
        bSysInfo = new javax.swing.JButton();
        bDonate = new javax.swing.JButton();
        opinionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informacion");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaInfo.setEditable(false);
        txtAreaInfo.setColumns(20);
        txtAreaInfo.setRows(5);
        txtAreaInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtAreaInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 600, 350));

        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        bCerrar.setContentAreaFilled(false);
        bCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bCerrarMouseMoved(evt);
            }
        });
        bCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bCerrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bCerrarMouseReleased(evt);
            }
        });
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 710, -1, -1));

        bSiguiente.setText("Siguiente");
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(bSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        bAnterior.setText("Anterior");
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(bAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        bSysInfo.setText("Información del Sistema");
        bSysInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSysInfoActionPerformed(evt);
            }
        });
        getContentPane().add(bSysInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));

        bDonate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paypaldonate.png"))); // NOI18N
        bDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDonateActionPerformed(evt);
            }
        });
        getContentPane().add(bDonate, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 630, 150, 120));

        opinionButton.setText("Déjanos saber tu opinión");
        opinionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opinionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(opinionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/construccion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Space_abstract_by_ScarArt.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCerrarActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        if (pageNumber==0) {
            pageNumber++;
        }
        checkPage();
        readInfo();
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void bCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMouseMoved
        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrarL.png")));
    }//GEN-LAST:event_bCerrarMouseMoved

    private void bCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMouseExited
        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png")));
    }//GEN-LAST:event_bCerrarMouseExited

    private void bCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMousePressed
        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrarP.png")));
    }//GEN-LAST:event_bCerrarMousePressed

    private void bCerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMouseReleased
        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png")));
    }//GEN-LAST:event_bCerrarMouseReleased

    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
        if (pageNumber==1) {
            pageNumber--;
        }
        checkPage();
        readInfo();
    }//GEN-LAST:event_bAnteriorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bSysInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSysInfoActionPerformed
        Ejecutar ejec = new Ejecutar();
        ejec.getSysInfo();
    }//GEN-LAST:event_bSysInfoActionPerformed

    private void bDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDonateActionPerformed
        Ejecutar ejec = new Ejecutar();
        ejec.linkOpenner("https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=excalibur_965%40hotmail%2ecom&lc=MX&item_name=Digital%20Open%20Project&item_number=dopmx&no_note=0&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHostedGuest");
    }//GEN-LAST:event_bDonateActionPerformed

    private void opinionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opinionButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetMsgMail().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_opinionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Info dialog = new Info(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bDonate;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JButton bSysInfo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton opinionButton;
    private javax.swing.JTextArea txtAreaInfo;
    // End of variables declaration//GEN-END:variables
}
