
/*
 * Office.java
 *
 * Created on 31/10/2012, 02:00:22 PM
 */

package nahum;

import java.util.Date;

/**
 *
 * @author Nahum Flores Gómez
 */
public class Office extends javax.swing.JDialog {
    private Ejecutar ejec = new Ejecutar();
    /** Creates new form Office */
    public Office(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Oficina");
        lWrite.setVisible(false);
        lCalc.setVisible(false);
        lPpt.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bWord = new javax.swing.JButton();
        bPP = new javax.swing.JButton();
        bCalc = new javax.swing.JButton();
        lWrite = new javax.swing.JLabel();
        lCalc = new javax.swing.JLabel();
        lPpt = new javax.swing.JLabel();
        bPdf = new javax.swing.JButton();
        fondoOffice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Oficina");
        setMaximumSize(new java.awt.Dimension(640, 427));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/word.png"))); // NOI18N
        bWord.setContentAreaFilled(false);
        bWord.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bWordMouseMoved(evt);
            }
        });
        bWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bWordMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bWordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bWordMouseReleased(evt);
            }
        });
        bWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bWordActionPerformed(evt);
            }
        });
        getContentPane().add(bWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 120));

        bPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ppt.png"))); // NOI18N
        bPP.setContentAreaFilled(false);
        bPP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bPPMouseMoved(evt);
            }
        });
        bPP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bPPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bPPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bPPMouseReleased(evt);
            }
        });
        bPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPPActionPerformed(evt);
            }
        });
        getContentPane().add(bPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 120, 120));

        bCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        bCalc.setContentAreaFilled(false);
        bCalc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bCalcMouseMoved(evt);
            }
        });
        bCalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCalcMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bCalcMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bCalcMouseReleased(evt);
            }
        });
        bCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcActionPerformed(evt);
            }
        });
        getContentPane().add(bCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 120, 120));

        lWrite.setForeground(new java.awt.Color(0, 204, 255));
        lWrite.setText("Documento");
        getContentPane().add(lWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        lCalc.setText("Hoja de cálculo");
        getContentPane().add(lCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        lPpt.setForeground(new java.awt.Color(102, 102, 255));
        lPpt.setText("Presentación");
        getContentPane().add(lPpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        bPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf-icon.png"))); // NOI18N
        bPdf.setContentAreaFilled(false);
        bPdf.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bPdfMouseMoved(evt);
            }
        });
        bPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bPdfMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bPdfMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bPdfMouseReleased(evt);
            }
        });
        bPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPdfActionPerformed(evt);
            }
        });
        getContentPane().add(bPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        fondoOffice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4435714890_2aa56d3f95_z.jpg"))); // NOI18N
        getContentPane().add(fondoOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Excecutes class Ejecutar method escritor
     * and save registry of the event in a txt file
     * @param evt 
     */
    private void bWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWordActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Word \nSe ejecuta Office Word\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        ejec.escritor();
        this.dispose();
    }//GEN-LAST:event_bWordActionPerformed

    private void bPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPPActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón PP \nSe ejecuta Office Power Point\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        ejec.presentador();
        this.dispose();
    }//GEN-LAST:event_bPPActionPerformed

    private void bCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Calc \nSe ejecuta Office Excel\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        ejec.calculo();
        this.dispose();
    }//GEN-LAST:event_bCalcActionPerformed

    private void bWordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bWordMouseExited
        bWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/word.png")));
        lWrite.setVisible(false);
    }//GEN-LAST:event_bWordMouseExited

    private void bWordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bWordMouseMoved
        bWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wordL.png")));
        lWrite.setVisible(true);
    }//GEN-LAST:event_bWordMouseMoved

    private void bWordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bWordMousePressed
        bWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wordP.png")));
    }//GEN-LAST:event_bWordMousePressed

    private void bWordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bWordMouseReleased
        bWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/word.png")));
    }//GEN-LAST:event_bWordMouseReleased

    private void bPPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPPMouseMoved
        bPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pptL.png")));
        lPpt.setVisible(true);
    }//GEN-LAST:event_bPPMouseMoved

    private void bPPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPPMouseExited
        bPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ppt.png")));
        lPpt.setVisible(false);
    }//GEN-LAST:event_bPPMouseExited

    private void bPPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPPMousePressed
        bPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pptP.png")));
    }//GEN-LAST:event_bPPMousePressed

    private void bPPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPPMouseReleased
        bPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ppt.png")));
    }//GEN-LAST:event_bPPMouseReleased

    private void bCalcMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCalcMouseMoved
        bCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excelL.png")));
        lCalc.setVisible(true);
    }//GEN-LAST:event_bCalcMouseMoved

    private void bCalcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCalcMouseExited
        bCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png")));
        lCalc.setVisible(false);
    }//GEN-LAST:event_bCalcMouseExited

    private void bCalcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCalcMousePressed
        bCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excelP.png")));
    }//GEN-LAST:event_bCalcMousePressed

    private void bCalcMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCalcMouseReleased
        bCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png")));
    }//GEN-LAST:event_bCalcMouseReleased

    private void bPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPdfActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Pdf \nSe ejecuta Adobe Reader\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        this.dispose();
        ejec.leerPDF();
    }//GEN-LAST:event_bPdfActionPerformed

    private void bPdfMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPdfMouseMoved
        bPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf-iconL.png")));
    }//GEN-LAST:event_bPdfMouseMoved

    private void bPdfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPdfMouseExited
        bPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf-icon.png")));
    }//GEN-LAST:event_bPdfMouseExited

    private void bPdfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPdfMousePressed
        bPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf-iconP.png")));
    }//GEN-LAST:event_bPdfMousePressed

    private void bPdfMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPdfMouseReleased
        bPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf-icon.png")));
    }//GEN-LAST:event_bPdfMouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Office dialog = new Office(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCalc;
    private javax.swing.JButton bPP;
    private javax.swing.JButton bPdf;
    private javax.swing.JButton bWord;
    private javax.swing.JLabel fondoOffice;
    private javax.swing.JLabel lCalc;
    private javax.swing.JLabel lPpt;
    private javax.swing.JLabel lWrite;
    // End of variables declaration//GEN-END:variables

}
