/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nahum;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author NahumFrog
 */
public class ShutdownSistem extends javax.swing.JDialog {
    Ejecutar ejec = new Ejecutar();
    /**
     * Creates new form ShutdownSistem
     */
    public ShutdownSistem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        checkTimerTxt();
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////
    private void callForPass(){//invoca la ventana para recibir la contraseña
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RequestUsrLinux dialog = new RequestUsrLinux(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////
    private void checkTimerTxt(){
        if (timerCheckBox.isSelected()) {
            timerTxt.setVisible(true);
            JOptionPane.showMessageDialog(null, "Por favor escriba la cantidad de tiempo en segundos\npara apagar el equipo");
            timerTxt.requestFocus();
            timerLabel.setVisible(true);
        }else{
            timerTxt.setVisible(false);
            timerLabel.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bApagar = new javax.swing.JButton();
        bReiniciar = new javax.swing.JButton();
        bSuspender = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bCancel = new javax.swing.JButton();
        timerCheckBox = new javax.swing.JCheckBox();
        timerTxt = new javax.swing.JTextField();
        timerLabel = new javax.swing.JLabel();
        lFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutdown.png"))); // NOI18N
        bApagar.setBorderPainted(false);
        bApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApagarActionPerformed(evt);
            }
        });
        getContentPane().add(bApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, -1));

        bReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/power_restart.png"))); // NOI18N
        bReiniciar.setBorderPainted(false);
        bReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(bReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 140, -1));

        bSuspender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar-sesion.png"))); // NOI18N
        bSuspender.setBorderPainted(false);
        bSuspender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSuspenderActionPerformed(evt);
            }
        });
        getContentPane().add(bSuspender, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 140, -1));

        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Apagar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Reiniciar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Cerrar Sesion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        bCancel.setText("Cancelar");
        bCancel.setBorderPainted(false);
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        getContentPane().add(bCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        timerCheckBox.setText("Temporizar");
        timerCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(timerCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(timerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 40, -1));

        timerLabel.setForeground(new java.awt.Color(204, 204, 255));
        timerLabel.setText("Tiempo");
        getContentPane().add(timerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        lFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/horizon.jpg"))); // NOI18N
        getContentPane().add(lFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApagarActionPerformed
        bReiniciar.setEnabled(false);
        bSuspender.setEnabled(false);
        ejec.reproSound("Config/system-shutting-down.wav");
        String os = System.getProperty("os.name");
        Date fecha = new Date();
        WriteRead leeEsc = new WriteRead();
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")||os.equalsIgnoreCase("Windows 10")) {
            if (timerCheckBox.isSelected()) {
                String time = timerTxt.getText();
                int tiempo = Integer.parseInt(time);
                ejec.timedShutDown(tiempo);
                leeEsc.escribeReg("Lisa apaga el equipo. \n"+fecha);
            }else{
                leeEsc.escribeReg("Lisa apaga el equipo. \n"+fecha);
                ejec.shutdownSistem();
            }
            
        }
        if (os.equalsIgnoreCase("Linux")) {
            JOptionPane.showMessageDialog(null, fecha, "Esta opción  sigue en prueba para linux\nfavor de reportar cualquier error", JOptionPane.INFORMATION_MESSAGE);
            callForPass();
        }
    }//GEN-LAST:event_bApagarActionPerformed

    private void bReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReiniciarActionPerformed
        ejec.restartSistem();
        bApagar.setEnabled(false);
        bSuspender.setEnabled(false);
        ejec.reproSound("Config/system-shutting-down.wav");
        String os = System.getProperty("os.name");
        Date fecha = new Date();
        WriteRead leeEsc = new WriteRead();
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")||os.equalsIgnoreCase("Windows 10")) {
            leeEsc.escribeReg("Lisa reinicia el equipo. \n"+fecha);
            
        }
        if (os.equalsIgnoreCase("Linux")) {
            
            JOptionPane.showMessageDialog(null, fecha, "Esta opción está habilitada para linux en modo de prueba\nfavor de reportar cualquier error", JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_bReiniciarActionPerformed

    private void bSuspenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSuspenderActionPerformed
        ejec.logOff();
        bApagar.setEnabled(false);
        bReiniciar.setEnabled(false);
        String os = System.getProperty("os.name");
        Date fecha = new Date();
        WriteRead leeEsc = new WriteRead();
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")||os.equalsIgnoreCase("Windows 10")) {
            leeEsc.escribeReg("Lisa cierra la sesion. \n"+fecha);
        }
        if (os.equalsIgnoreCase("Linux")) {
            JOptionPane.showMessageDialog(null, fecha, "Esta opción  no esta habilitada para linux\nfavor de reportar cualquier error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bSuspenderActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void timerCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerCheckBoxActionPerformed
        checkTimerTxt();
    }//GEN-LAST:event_timerCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShutdownSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShutdownSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShutdownSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShutdownSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShutdownSistem dialog = new ShutdownSistem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bApagar;
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bReiniciar;
    private javax.swing.JButton bSuspender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lFondo;
    private javax.swing.JCheckBox timerCheckBox;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JTextField timerTxt;
    // End of variables declaration//GEN-END:variables
}
