

package nahum;

import java.awt.Toolkit;


/**
 *
 * @author nahumfg
 */
public class Software extends javax.swing.JDialog {
    private Ejecutar ejec = new Ejecutar();
    /**
     * Creates new form Software
     */
    public Software(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/images/emblem-linux.png")));
        this.setLocationRelativeTo(null);
        labelArduino.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        bArduino = new javax.swing.JButton();
        bBluetooth = new javax.swing.JButton();
        bDataBase = new javax.swing.JButton();
        webShortcutButton = new javax.swing.JButton();
        labelArduino = new javax.swing.JLabel();
        lFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sofrware");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setText("Cerrar Ventana");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        bArduino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arduino.png"))); // NOI18N
        bArduino.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bArduinoMouseMoved(evt);
            }
        });
        bArduino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bArduinoMouseExited(evt);
            }
        });
        bArduino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArduinoActionPerformed(evt);
            }
        });
        getContentPane().add(bArduino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 130));

        bBluetooth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bluetooth.png"))); // NOI18N
        bBluetooth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBluetoothActionPerformed(evt);
            }
        });
        getContentPane().add(bBluetooth, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 140, 130));

        bDataBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base-datos.png"))); // NOI18N
        bDataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataBaseActionPerformed(evt);
            }
        });
        getContentPane().add(bDataBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 150, 130));

        webShortcutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/web.png"))); // NOI18N
        webShortcutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webShortcutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(webShortcutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 150, 130));

        labelArduino.setText("Arduino");
        getContentPane().add(labelArduino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        lFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/software.jpg"))); // NOI18N
        getContentPane().add(lFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void bDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDBActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PassDB dialog = new PassDB(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_bDBActionPerformed

    private void bArduinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArduinoActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arduino().setVisible(true);
            }
        });
    }//GEN-LAST:event_bArduinoActionPerformed

    private void bBluetoothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBluetoothActionPerformed
        ejec.bluetoothTool();
    }//GEN-LAST:event_bBluetoothActionPerformed

    private void bDataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataBaseActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PassDB dialog = new PassDB(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_bDataBaseActionPerformed

    private void webShortcutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webShortcutButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WebShotrCuts().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_webShortcutButtonActionPerformed

    private void bArduinoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bArduinoMouseMoved
        labelArduino.setVisible(true);
    }//GEN-LAST:event_bArduinoMouseMoved

    private void bArduinoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bArduinoMouseExited
        labelArduino.setVisible(false);
    }//GEN-LAST:event_bArduinoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Software dialog = new Software(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bArduino;
    private javax.swing.JButton bBluetooth;
    private javax.swing.JButton bDataBase;
    private javax.swing.JLabel lFondo;
    private javax.swing.JLabel labelArduino;
    private javax.swing.JButton salir;
    private javax.swing.JButton webShortcutButton;
    // End of variables declaration//GEN-END:variables
}
