/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Utils.java
 *
 * Created on 31/10/2012, 02:01:00 PM
 */

package nahum;

import java.util.Date;

/**
 *
 * @author Nahum Flores Gómez
 */
public class Utils extends javax.swing.JDialog {
    private Ejecutar ejec = new Ejecutar();
    /** Creates new form Utils */
    public Utils(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Utilerias");
        lAdmin.setVisible(false);
        lCalc.setVisible(false);
        lTerminal.setVisible(false);
        lFolder.setVisible(false);
        lTxt.setVisible(false);
        lSoft.setVisible(false);
        lProc.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bFolder = new javax.swing.JButton();
        bTerminal = new javax.swing.JButton();
        bText = new javax.swing.JButton();
        bCalculadora = new javax.swing.JButton();
        bProcessAdmin = new javax.swing.JButton();
        lTerminal = new javax.swing.JLabel();
        lCalc = new javax.swing.JLabel();
        lFolder = new javax.swing.JLabel();
        lAdmin = new javax.swing.JLabel();
        lTxt = new javax.swing.JLabel();
        bInstall = new javax.swing.JButton();
        lSoft = new javax.swing.JLabel();
        bListaP = new javax.swing.JButton();
        lProc = new javax.swing.JLabel();
        fondoutils = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Utilerias");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carpeta.png"))); // NOI18N
        bFolder.setContentAreaFilled(false);
        bFolder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bFolderMouseMoved(evt);
            }
        });
        bFolder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bFolderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bFolderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bFolderMouseReleased(evt);
            }
        });
        bFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFolderActionPerformed(evt);
            }
        });
        getContentPane().add(bFolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 130, -1));

        bTerminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/terminal.png"))); // NOI18N
        bTerminal.setContentAreaFilled(false);
        bTerminal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bTerminalMouseMoved(evt);
            }
        });
        bTerminal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bTerminalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bTerminalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bTerminalMouseReleased(evt);
            }
        });
        bTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTerminalActionPerformed(evt);
            }
        });
        getContentPane().add(bTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 150, 120));

        bText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kJQko.png"))); // NOI18N
        bText.setContentAreaFilled(false);
        bText.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bTextMouseMoved(evt);
            }
        });
        bText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bTextMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bTextMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bTextMouseReleased(evt);
            }
        });
        bText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTextActionPerformed(evt);
            }
        });
        getContentPane().add(bText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 140, -1));

        bCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Simulador_calculadora.png"))); // NOI18N
        bCalculadora.setContentAreaFilled(false);
        bCalculadora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bCalculadoraMouseMoved(evt);
            }
        });
        bCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCalculadoraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bCalculadoraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bCalculadoraMouseReleased(evt);
            }
        });
        bCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalculadoraActionPerformed(evt);
            }
        });
        getContentPane().add(bCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 130, 130));

        bProcessAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        bProcessAdmin.setContentAreaFilled(false);
        bProcessAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bProcessAdminMouseMoved(evt);
            }
        });
        bProcessAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bProcessAdminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bProcessAdminMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bProcessAdminMouseReleased(evt);
            }
        });
        bProcessAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcessAdminActionPerformed(evt);
            }
        });
        getContentPane().add(bProcessAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 150, 130));

        lTerminal.setForeground(new java.awt.Color(51, 204, 255));
        lTerminal.setText("Línea de comandos");
        getContentPane().add(lTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lCalc.setForeground(new java.awt.Color(102, 153, 255));
        lCalc.setText("Calculadora");
        getContentPane().add(lCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        lFolder.setForeground(new java.awt.Color(102, 255, 102));
        lFolder.setText("Archivos");
        getContentPane().add(lFolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        lAdmin.setText("Monitor del Sistema");
        getContentPane().add(lAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        lTxt.setText("Bloc de Notas");
        getContentPane().add(lTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        bInstall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Downloads.png"))); // NOI18N
        bInstall.setContentAreaFilled(false);
        bInstall.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bInstallMouseMoved(evt);
            }
        });
        bInstall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bInstallMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bInstallMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bInstallMouseReleased(evt);
            }
        });
        bInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInstallActionPerformed(evt);
            }
        });
        getContentPane().add(bInstall, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 140, -1));

        lSoft.setText("Gestor de control Y Software");
        getContentPane().add(lSoft, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        bListaP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/process.png"))); // NOI18N
        bListaP.setContentAreaFilled(false);
        bListaP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bListaPMouseMoved(evt);
            }
        });
        bListaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bListaPMouseExited(evt);
            }
        });
        bListaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListaPActionPerformed(evt);
            }
        });
        getContentPane().add(bListaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 140, -1));

        lProc.setText("Listar Procesos Actuales");
        getContentPane().add(lProc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        fondoutils.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-master-aplicacion-para-proteger-tus-archivos-con-contraseñas.jpg"))); // NOI18N
        getContentPane().add(fondoutils, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTerminalActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Terminal \nse ejecuta la línea de comandos\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        this.dispose();
        ejec.terminal();
        
    }//GEN-LAST:event_bTerminalActionPerformed

    private void bTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTextActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Text \nSe ejecuta editor de texto\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        this.dispose();
        ejec.text();
        
    }//GEN-LAST:event_bTextActionPerformed

    private void bFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFolderActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Folder \nSe ejecuta gestor de archivos\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        this.dispose();
        ejec.folder();
        
    }//GEN-LAST:event_bFolderActionPerformed

    private void bCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalculadoraActionPerformed
        
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Calculadora \nSe ejecuta calculadora\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }this.dispose();
        ejec.calculadora();
        
    }//GEN-LAST:event_bCalculadoraActionPerformed

    private void bProcessAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcessAdminActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón ProcessAdmin \nSe ejecuta Supervisor de tareas\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        this.dispose();
        ejec.processAdmin();
        
    }//GEN-LAST:event_bProcessAdminActionPerformed

    private void bTerminalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTerminalMouseMoved
        bTerminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/terminalL.png")));
        lTerminal.setVisible(true);
    }//GEN-LAST:event_bTerminalMouseMoved

    private void bTerminalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTerminalMouseExited
        bTerminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/terminal.png")));
        lTerminal.setVisible(false);
    }//GEN-LAST:event_bTerminalMouseExited

    private void bTerminalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTerminalMousePressed
        bTerminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/terminalP.png")));
    }//GEN-LAST:event_bTerminalMousePressed

    private void bTerminalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTerminalMouseReleased
        bTerminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/terminal.png")));
    }//GEN-LAST:event_bTerminalMouseReleased

    private void bFolderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFolderMouseMoved
         bFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carpetaL.png")));
         lFolder.setVisible(true);
    }//GEN-LAST:event_bFolderMouseMoved

    private void bFolderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFolderMouseExited
         bFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carpeta.png")));
         lFolder.setVisible(false);
    }//GEN-LAST:event_bFolderMouseExited

    private void bFolderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFolderMousePressed
         bFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carpetaP.png")));
    }//GEN-LAST:event_bFolderMousePressed

    private void bFolderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFolderMouseReleased
         bFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carpeta.png")));
    }//GEN-LAST:event_bFolderMouseReleased

    private void bProcessAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProcessAdminMouseMoved
        bProcessAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminL.png")));
        lAdmin.setVisible(true);
    }//GEN-LAST:event_bProcessAdminMouseMoved

    private void bProcessAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProcessAdminMouseExited
        bProcessAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png")));
        lAdmin.setVisible(false);
    }//GEN-LAST:event_bProcessAdminMouseExited

    private void bProcessAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProcessAdminMousePressed
        bProcessAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminP.png")));
    }//GEN-LAST:event_bProcessAdminMousePressed

    private void bProcessAdminMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProcessAdminMouseReleased
        bProcessAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png")));
    }//GEN-LAST:event_bProcessAdminMouseReleased

    private void bTextMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTextMouseMoved
        bText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kJQkoL.png")));
        lTxt.setVisible(true);
    }//GEN-LAST:event_bTextMouseMoved

    private void bTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTextMouseExited
        bText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kJQko.png")));
        lTxt.setVisible(false);
    }//GEN-LAST:event_bTextMouseExited

    private void bTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTextMousePressed
        bText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kJQkoP.png")));
    }//GEN-LAST:event_bTextMousePressed

    private void bTextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTextMouseReleased
        bText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kJQko.png")));
    }//GEN-LAST:event_bTextMouseReleased

    private void bCalculadoraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCalculadoraMouseMoved
        bCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Simulador_calculadoraL.png")));
        lCalc.setVisible(true);
    }//GEN-LAST:event_bCalculadoraMouseMoved

    private void bCalculadoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCalculadoraMouseExited
        bCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Simulador_calculadora.png")));
        lCalc.setVisible(false);
    }//GEN-LAST:event_bCalculadoraMouseExited

    private void bCalculadoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCalculadoraMousePressed
        bCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Simulador_calculadoraP.png")));
    }//GEN-LAST:event_bCalculadoraMousePressed

    private void bCalculadoraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCalculadoraMouseReleased
        bCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Simulador_calculadora.png")));
    }//GEN-LAST:event_bCalculadoraMouseReleased

    private void bInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInstallActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Install \nSe ejecuta panel de control\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        this.dispose();
        ejec.instalador();
    }//GEN-LAST:event_bInstallActionPerformed

    private void bInstallMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInstallMouseMoved
        bInstall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DownloadsL.png")));
        lSoft.setVisible(true);
    }//GEN-LAST:event_bInstallMouseMoved

    private void bInstallMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInstallMouseExited
        bInstall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Downloads.png")));
        lSoft.setVisible(false);
    }//GEN-LAST:event_bInstallMouseExited

    private void bInstallMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInstallMousePressed
        bInstall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DownloadsP.png")));
    }//GEN-LAST:event_bInstallMousePressed

    private void bInstallMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInstallMouseReleased
        bInstall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Downloads.png")));
    }//GEN-LAST:event_bInstallMouseReleased

    private void bListaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListaPActionPerformed
        
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Lista \nSe abrió una lista de procesos ejecutados\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Procesos().setVisible(true);
            }
        });
        System.gc();
    }//GEN-LAST:event_bListaPActionPerformed

    private void bListaPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bListaPMouseMoved
        lProc.setVisible(true);
    }//GEN-LAST:event_bListaPMouseMoved

    private void bListaPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bListaPMouseExited
        lProc.setVisible(false);
    }//GEN-LAST:event_bListaPMouseExited

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Utils dialog = new Utils(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCalculadora;
    private javax.swing.JButton bFolder;
    private javax.swing.JButton bInstall;
    private javax.swing.JButton bListaP;
    private javax.swing.JButton bProcessAdmin;
    private javax.swing.JButton bTerminal;
    private javax.swing.JButton bText;
    private javax.swing.JLabel fondoutils;
    private javax.swing.JLabel lAdmin;
    private javax.swing.JLabel lCalc;
    private javax.swing.JLabel lFolder;
    private javax.swing.JLabel lProc;
    private javax.swing.JLabel lSoft;
    private javax.swing.JLabel lTerminal;
    private javax.swing.JLabel lTxt;
    // End of variables declaration//GEN-END:variables

}
