

/*
 * Web.java
 *
 * Created on 31/10/2012, 02:01:12 PM
 */

package nahum;

import java.util.Date;

/**
 *
 * @author Nahum Flores Gómez
 */
public class Web extends javax.swing.JDialog {
    private Ejecutar ejec = new Ejecutar();
    private final String OS = System.getProperty("os.name");
    /** Creates new form Web */
    public Web(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        
        initComponents();
        this.setLocationRelativeTo(null);
        if(OS.equalsIgnoreCase("Linux")){
            bMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chat-icon.png")));
        }else{
            bMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Skype-icon-128x128.png")));
            if (OS.equalsIgnoreCase("Windows 8")||OS.equalsIgnoreCase("Windows 8.1")) {
                bMessage.setVisible(false);
            }
        }
        this.setTitle("Navegación Web");
        lFirefox.setVisible(false);
        lChrome.setVisible(false);
        lExplore.setVisible(false);
        lMessage.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bFirefox = new javax.swing.JButton();
        bIExplore = new javax.swing.JButton();
        bChrome = new javax.swing.JButton();
        bMessage = new javax.swing.JButton();
        lFirefox = new javax.swing.JLabel();
        lChrome = new javax.swing.JLabel();
        lExplore = new javax.swing.JLabel();
        lMessage = new javax.swing.JLabel();
        fondoWeb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Navegadores Web");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bFirefox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Firefox.png"))); // NOI18N
        bFirefox.setBorderPainted(false);
        bFirefox.setContentAreaFilled(false);
        bFirefox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bFirefoxMouseMoved(evt);
            }
        });
        bFirefox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bFirefoxMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bFirefoxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bFirefoxMouseReleased(evt);
            }
        });
        bFirefox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFirefoxActionPerformed(evt);
            }
        });
        getContentPane().add(bFirefox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, -1));

        bIExplore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iexplorer.png"))); // NOI18N
        bIExplore.setBorderPainted(false);
        bIExplore.setContentAreaFilled(false);
        bIExplore.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bIExploreMouseMoved(evt);
            }
        });
        bIExplore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bIExploreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bIExploreMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bIExploreMouseReleased(evt);
            }
        });
        bIExplore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIExploreActionPerformed(evt);
            }
        });
        getContentPane().add(bIExplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        bChrome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Google chrome.png"))); // NOI18N
        bChrome.setBorderPainted(false);
        bChrome.setContentAreaFilled(false);
        bChrome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bChromeMouseMoved(evt);
            }
        });
        bChrome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bChromeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bChromeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bChromeMouseReleased(evt);
            }
        });
        bChrome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChromeActionPerformed(evt);
            }
        });
        getContentPane().add(bChrome, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 220, -1));

        bMessage.setBorderPainted(false);
        bMessage.setContentAreaFilled(false);
        bMessage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bMessageMouseMoved(evt);
            }
        });
        bMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMessageMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bMessageMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bMessageMouseReleased(evt);
            }
        });
        bMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMessageActionPerformed(evt);
            }
        });
        getContentPane().add(bMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        lFirefox.setText("Firefox");
        getContentPane().add(lFirefox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lChrome.setText("Chrome");
        getContentPane().add(lChrome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        lExplore.setText("Internet Explorer");
        getContentPane().add(lExplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        lMessage.setText("Mensajería");
        getContentPane().add(lMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        fondoWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/web-image_2261720b.jpg"))); // NOI18N
        getContentPane().add(fondoWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFirefoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFirefoxActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="";
        if (OS.equalsIgnoreCase("Windos 7")||OS.equalsIgnoreCase("Windows 8")||OS.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Firefox \nSe ejecuta Navegador Firefox\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        this.dispose();
        ejec.firefox();
        
    }//GEN-LAST:event_bFirefoxActionPerformed

    private void bChromeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChromeActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="";
        if (OS.equalsIgnoreCase("Windos 7")||OS.equalsIgnoreCase("Windows 8")||OS.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Chrome \nSe ejecuta Google Chrome\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        this.dispose();
        ejec.chrome();
        
    }//GEN-LAST:event_bChromeActionPerformed

    private void bIExploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIExploreActionPerformed
        WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="";
        if (OS.equalsIgnoreCase("Windos 7")||OS.equalsIgnoreCase("Windows 8")||OS.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón IExplore \nSe ejecuta Internet Explorer\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
        this.dispose();
        ejec.winIExplore();
        
    }//GEN-LAST:event_bIExploreActionPerformed

    private void bFirefoxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFirefoxMouseMoved
        bFirefox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FirefoxL.png")));
        lFirefox.setVisible(true);
    }//GEN-LAST:event_bFirefoxMouseMoved

    private void bFirefoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFirefoxMouseExited
        bFirefox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Firefox.png")));
        lFirefox.setVisible(false);
    }//GEN-LAST:event_bFirefoxMouseExited

    private void bFirefoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFirefoxMousePressed
        bFirefox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FirefoxP.png")));
    }//GEN-LAST:event_bFirefoxMousePressed

    private void bFirefoxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFirefoxMouseReleased
        bFirefox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Firefox.png")));
    }//GEN-LAST:event_bFirefoxMouseReleased

    private void bMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMessageActionPerformed
        if (OS.equalsIgnoreCase("Windows 8")||OS.equalsIgnoreCase("Windows 8.1")) {
            
        }else{
            WriteRead leeEsc = new WriteRead();
        Date fecha = new Date();
        String registro="",os=System.getProperty("os.name");
        if (os.equalsIgnoreCase("Windos 7")||os.equalsIgnoreCase("Windows 8")||os.equalsIgnoreCase("Windows 8.1")) {
            registro = registro + "Registro fecha: "+fecha+"\n";
            registro = registro + "--------------------------------------\n";
            registro = registro + "Fue presionado el botón Message \nSe ejecuta Skype\n";
            registro = registro + "--------------------------------------\n";
            leeEsc.escribeReg(registro);
        }
            this.dispose();
            ejec.instanMessage();
            
        }
        
    }//GEN-LAST:event_bMessageActionPerformed

    private void bChromeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bChromeMouseMoved
        bChrome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Google chromeL.png")));
        lChrome.setVisible(true);
    }//GEN-LAST:event_bChromeMouseMoved

    private void bChromeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bChromeMouseExited
        bChrome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Google chrome.png")));
        lChrome.setVisible(false);
    }//GEN-LAST:event_bChromeMouseExited

    private void bChromeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bChromeMousePressed
        bChrome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Google chromeP.png")));
    }//GEN-LAST:event_bChromeMousePressed

    private void bChromeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bChromeMouseReleased
        bChrome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Google chrome.png")));
    }//GEN-LAST:event_bChromeMouseReleased

    private void bIExploreMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIExploreMouseMoved
        bIExplore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iexplorerL.png")));
        lExplore.setVisible(true);
    }//GEN-LAST:event_bIExploreMouseMoved

    private void bIExploreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIExploreMouseExited
        bIExplore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iexplorer.png")));
        lExplore.setVisible(false);
    }//GEN-LAST:event_bIExploreMouseExited

    private void bIExploreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIExploreMousePressed
        bIExplore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iexplorerP.png")));
    }//GEN-LAST:event_bIExploreMousePressed

    private void bIExploreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIExploreMouseReleased
        bIExplore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iexplorer.png")));
    }//GEN-LAST:event_bIExploreMouseReleased

    private void bMessageMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMessageMouseMoved
        lMessage.setVisible(true);
        if(OS.equalsIgnoreCase("Linux")){
            bMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chat-iconL.png")));
        }else{
            bMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Skype-icon-128x128L.png")));
        }
    }//GEN-LAST:event_bMessageMouseMoved

    private void bMessageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMessageMouseExited
        lMessage.setVisible(false);
        if(OS.equalsIgnoreCase("Linux")){
            bMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chat-icon.png")));
        }else{
            bMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Skype-icon-128x128.png")));
        }
    }//GEN-LAST:event_bMessageMouseExited

    private void bMessageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMessageMousePressed
        if(OS.equalsIgnoreCase("Linux")){
            bMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chat-iconP.png")));
        }else{
            bMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Skype-icon-128x128P.png")));
        }
    }//GEN-LAST:event_bMessageMousePressed

    private void bMessageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMessageMouseReleased
        if(OS.equalsIgnoreCase("Linux")){
            bMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chat-icon.png")));
        }else{
            bMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Skype-icon-128x128.png")));
        }
    }//GEN-LAST:event_bMessageMouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Web dialog = new Web(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bChrome;
    private javax.swing.JButton bFirefox;
    private javax.swing.JButton bIExplore;
    private javax.swing.JButton bMessage;
    private javax.swing.JLabel fondoWeb;
    private javax.swing.JLabel lChrome;
    private javax.swing.JLabel lExplore;
    private javax.swing.JLabel lFirefox;
    private javax.swing.JLabel lMessage;
    // End of variables declaration//GEN-END:variables

}
