/*
 * Copyright (c) 2016, NahumFrog
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package nahum;

import java.awt.Toolkit;

/**
 *
 * @author NahumFrog
 */
public class WebShotrCuts extends javax.swing.JFrame {

    /**
     * Creates new form webShotrCuts
     */
    public WebShotrCuts() {
        initComponents();
        this.setLocation(256, 100);
    }

    private Ejecutar ejec = new Ejecutar();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blenderWebButton = new javax.swing.JButton();
        fbBlenderWebButton = new javax.swing.JButton();
        mkHumanWebButton = new javax.swing.JButton();
        gWebButton = new javax.swing.JButton();
        youtubeWebButton = new javax.swing.JButton();
        donativeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Accesos Web de Interés");
        setBackground(new java.awt.Color(204, 255, 255));
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/images/emblem-linux.png")));

        blenderWebButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Blender-icon.png"))); // NOI18N
        blenderWebButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blenderWebButtonActionPerformed(evt);
            }
        });

        fbBlenderWebButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook-icono-7180-64.png"))); // NOI18N
        fbBlenderWebButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbBlenderWebButtonActionPerformed(evt);
            }
        });

        mkHumanWebButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mkhuman.png"))); // NOI18N
        mkHumanWebButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mkHumanWebButtonActionPerformed(evt);
            }
        });

        gWebButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/google_favicon_64.png"))); // NOI18N
        gWebButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gWebButtonActionPerformed(evt);
            }
        });

        youtubeWebButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Youtube_logo.png"))); // NOI18N
        youtubeWebButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youtubeWebButtonActionPerformed(evt);
            }
        });

        donativeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paypaldonate.png"))); // NOI18N
        donativeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donativeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blenderWebButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fbBlenderWebButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mkHumanWebButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gWebButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(youtubeWebButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(donativeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(youtubeWebButton)
                    .addComponent(gWebButton)
                    .addComponent(mkHumanWebButton)
                    .addComponent(fbBlenderWebButton)
                    .addComponent(blenderWebButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(donativeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blenderWebButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blenderWebButtonActionPerformed
        ejec.linkOpenner("https://www.blender.org/");
        
    }//GEN-LAST:event_blenderWebButtonActionPerformed

    private void fbBlenderWebButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbBlenderWebButtonActionPerformed
        ejec.linkOpenner("https://www.facebook.com/");
    }//GEN-LAST:event_fbBlenderWebButtonActionPerformed

    private void mkHumanWebButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkHumanWebButtonActionPerformed
        ejec.linkOpenner("http://www.makehuman.org/");
    }//GEN-LAST:event_mkHumanWebButtonActionPerformed

    private void gWebButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gWebButtonActionPerformed
        ejec.linkOpenner("https://www.google.com");
    }//GEN-LAST:event_gWebButtonActionPerformed

    private void youtubeWebButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youtubeWebButtonActionPerformed
        ejec.linkOpenner("https://www.youtube.com");
    }//GEN-LAST:event_youtubeWebButtonActionPerformed

    private void donativeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donativeButtonActionPerformed
        ejec.linkOpenner("https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=excalibur_965%40hotmail%2ecom&lc=MX&item_name=Digital%20Open%20Project&item_number=dopmx&no_note=0&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHostedGuest");
    }//GEN-LAST:event_donativeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebShotrCuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebShotrCuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebShotrCuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebShotrCuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WebShotrCuts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blenderWebButton;
    private javax.swing.JButton donativeButton;
    private javax.swing.JButton fbBlenderWebButton;
    private javax.swing.JButton gWebButton;
    private javax.swing.JButton mkHumanWebButton;
    private javax.swing.JButton youtubeWebButton;
    // End of variables declaration//GEN-END:variables
}
